services:
  namenode:
    image: apache/hadoop:3.4.1
    container_name: namenode
    hostname: namenode
    platform: linux/amd64
    user: root
    ports:
      - "9870:9870"     # Web UI NameNode
      - "9000:9000"     # RPC HDFS
      - "9001:9001"     # RPC Service NameNode
    volumes:
      - ./namenode_data:/hadoop/dfs/name
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
      - ./dataset:/dataset   # Carpeta local con CSV, etc.
    command: >
      bash -c "
      if [ ! -d /hadoop/dfs/name/current ]; then
        mkdir -p /hadoop/dfs/name &&
        /opt/hadoop/bin/hdfs namenode -format;
      fi &&
      /opt/hadoop/bin/hdfs namenode
      "

  datanode:
    image: apache/hadoop:3.4.1
    container_name: datanode
    hostname: datanode
    platform: linux/amd64
    depends_on:
      - namenode
    ports:
      - "9864:9864"     # Web UI DataNode
    volumes:
      - ./datanode_data:/hadoop/dfs/data
      - ./config/core-site.xml:/opt/hadoop/etc/hadoop/core-site.xml
      - ./config/hdfs-site.xml:/opt/hadoop/etc/hadoop/hdfs-site.xml
    command: >
      bash -c "
      mkdir -p /hadoop/dfs/data &&
      /opt/hadoop/bin/hdfs datanode
      "

  metastore:
    image: bde2020/hive-metastore-postgresql:latest
    container_name: metastore
    hostname: metastore
    platform: linux/amd64
    depends_on:
      - namenode
      - datanode
    ports:
      - "9083:9083"  # Puerto Thrift del Metastore
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
      # dejamos que la imagen use su start-metastore-postgresql
    

  hive-server:
    image: bde2020/hive:latest
    container_name: hive-server
    hostname: hive-server
    platform: linux/amd64
    depends_on:
      - metastore
    ports:
      - "10000:10000"   # Para Beeline / JDBC
    volumes:
      - ./config/hive-site.xml:/opt/hive/conf/hive-site.xml
    environment:
      CORE_CONF_fs_defaultFS: "hdfs://namenode:9000"
      # Avisamos al HiveServer dónde está el Metastore
      HIVE_METASTORE_URI: "thrift://metastore:9083"
      HIVE_SERVER2_THRIFT_BIND_HOST: "0.0.0.0"
      HIVE_SERVER2_THRIFT_PORT: "10000"
    command: ["/opt/hive/bin/hive", "--service", "hiveserver2"]

volumes:
  namenode_data:
  datanode_data: